// Highlighted sidebar items
export const NEW = [
  'Shape Waves',
  'Aero Shards',
  'Ghost Fibers',
  'Infinite Spiral',
  'CRT Warp',
  'Glow Cursor',
  'Scroll Expand',
  'Ripple Distortion',
  'Depth Carousel',
  'Morph Slider',
  'Drift Wall',
  'Particle Text',
  'Split Flap Text',
  'Warp Text',
  'Depth Text',
  'Text Loop',
  'Molten Metal',
  'Gradient Waves',
  'Web Threads'
];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Introduction', 'Installation', 'MCP', 'Index']
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Text Loop',
      'Masked Heading',
      'Particle Text',
      'Split Flap Text',
      'Warp Text',
      'Stroke Text',
      'Depth Text',
      'Fold Text',
      'Echo Text',
      'Split Text',
      'Blur Text',
      'Circular Text',
      'Text Type',
      'Shuffle',
      'Shiny Text',
      'Text Pressure',
      'Curved Loop',
      'Fuzzy Text',
      'Gradient Text',
      'Falling Text',
      'Text Cursor',
      'Decrypted Text',
      'True Focus',
      'Scroll Float',
      'Scroll Reveal',
      'ASCII Text',
      'Scrambled Text',
      'Rotating Text',
      'Glitch Text',
      'Scroll Velocity',
      'Variable Proximity',
      'Count Up'
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Glow Cursor',
      'Scroll Expand',
      'Ripple Distortion',
      'Elastic Mesh',
      'Swarm Cursor',
      'Halftone Reveal',
      'Pixel Swap',
      'Cursor Grid',
      'Animated Content',
      'Fade Content',
      'Electric Border',
      'Orbit Images',
      'Pixel Transition',
      'Glare Hover',
      'Antigravity',
      'Logo Loop',
      'Target Cursor',
      'Magic Rings',
      'Laser Flow',
      'Magnet Lines',
      'Ghost Cursor',
      'Gradual Blur',
      'Click Spark',
      'Magnet',
      'Strands',
      'Sticker Peel',
      'Pixel Trail',
      'Cubes',
      'Metallic Paint',
      'Noise',
      'Shape Blur',
      'Crosshair',
      'Image Trail',
      'Ribbons',
      'Splash Cursor',
      'Meta Balls',
      'Blob Cursor',
      'Star Border'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Infinite Spiral',
      'Depth Carousel',
      'Morph Slider',
      'Drift Wall',
      'Accordion Gallery',
      'Specular Button',
      'Option Wheel',
      'Curved Input',
      'Line Sidebar',
      'Animated List',
      'Scroll Stack',
      'Bubble Menu',
      'Magic Bento',
      'Circular Gallery',
      'Reflective Card',
      'Card Nav',
      'Stack',
      'Fluid Glass',
      'Pill Nav',
      'Tilted Card',
      'Masonry',
      'Glass Surface',
      'Dome Gallery',
      'Chroma Grid',
      'Folder',
      'Staggered Menu',
      'Model Viewer',
      'Lanyard',
      'Profile Card',
      'Dock',
      'Gooey Nav',
      'Pixel Card',
      'Carousel',
      'Spotlight Card',
      'Border Glow',
      'Flying Posters',
      'Card Swap',
      'Glass Icons',
      'Decay Card',
      'Flowing Menu',
      'Elastic Slider',
      'Counter',
      'Infinite Menu',
      'Stepper',
      'Bounce Cards'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Shape Waves',
      'Aero Shards',
      'Ghost Fibers',
      'CRT Warp',
      'Molten Metal',
      'Gradient Waves',
      'Web Threads',
      'Topography',
      'Light Tunnel',
      'Sliced Waves',
      'Acid Squares',
      'Scanner',
      'Ferrofluid',
      'Lightfall',
      'Liquid Ether',
      'Prism',
      'Dark Veil',
      'Light Pillar',
      'Silk',
      'Floating Lines',
      'Side Rays',
      'Light Rays',
      'Pixel Blast',
      'Color Bends',
      'Evil Eye',
      'Line Waves',
      'Radar',
      'Soft Aurora',
      'Aurora',
      'Plasma',
      'Plasma Wave',
      'Particles',
      'Gradient Blinds',
      'Grainient',
      'Grid Scan',
      'Beams',
      'Pixel Snow',
      'Lightning',
      'Prismatic Burst',
      'Galaxy',
      'Dither',
      'Faulty Terminal',
      'Ripple Grid',
      'Dot Field',
      'Dot Grid',
      'Threads',
      'Hyperspeed',
      'Iridescence',
      'Waves',
      'Grid Distortion',
      'Ballpit',
      'Orb',
      'Letter Glitch',
      'Grid Motion',
      'Shape Grid',
      'Liquid Chrome',
      'Balatro'
    ]
  }
];

export const COMPONENT_COUNT = Math.floor(
  CATEGORIES.filter((c) => c.name !== 'Get Started').reduce((sum, c) => sum + c.subcategories.length, 0) / 5
) * 5;

export const TOTAL_COMPONENTS = CATEGORIES.filter(category => category.name !== 'Get Started').reduce(
  (total, category) => total + category.subcategories.length,
  0
);
