// Highlighted sidebar items
export const NEW = [
  'Liquid Ether',
  'Shuffle',
  'Laser Flow',
  'Ghost Cursor',
  'Color Bends',
  'Grid Scan',
  'Floating Lines',
  'Light Pillar',
  'Antigravity',
  'Reflective Card',
  'Pixel Snow'
];
export const UPDATED = ['Shiny Text', 'Fuzzy Text', 'Gradient Text', 'Electric Border', 'Flowing Menu'];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: ['Introduction', 'Installation', 'MCP', 'Index']
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Split Text',
      'Blur Text',
      'Circular Text',
      'Text Type',
      'Shuffle',
      'Shiny Text',
      'Text Pressure',
      'Curved Loop',
      'Fuzzy Text',
      'Gradient Text',
      'Falling Text',
      'Text Cursor',
      'Decrypted Text',
      'True Focus',
      'Scroll Float',
      'Scroll Reveal',
      'ASCII Text',
      'Scrambled Text',
      'Rotating Text',
      'Glitch Text',
      'Scroll Velocity',
      'Variable Proximity',
      'Count Up'
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Fade Content',
      'Electric Border',
      'Pixel Transition',
      'Glare Hover',
      'Antigravity',
      'Logo Loop',
      'Target Cursor',
      'Laser Flow',
      'Magnet Lines',
      'Ghost Cursor',
      'Gradual Blur',
      'Click Spark',
      'Magnet',
      'Sticker Peel',
      'Pixel Trail',
      'Cubes',
      'Metallic Paint',
      'Noise',
      'Shape Blur',
      'Crosshair',
      'Image Trail',
      'Ribbons',
      'Splash Cursor',
      'Meta Balls',
      'Blob Cursor',
      'Star Border'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Scroll Stack',
      'Bubble Menu',
      'Magic Bento',
      'Circular Gallery',
      'Reflective Card',
      'Card Nav',
      'Stack',
      'Fluid Glass',
      'Pill Nav',
      'Tilted Card',
      'Masonry',
      'Glass Surface',
      'Dome Gallery',
      'Chroma Grid',
      'Folder',
      'Staggered Menu',
      'Model Viewer',
      'Lanyard',
      'Profile Card',
      'Recipe Card',
      'Dock',
      'Gooey Nav',
      'Pixel Card',
      'Carousel',
      'Spotlight Card',
      'Flying Posters',
      'Card Swap',
      'Glass Icons',
      'Decay Card',
      'Flowing Menu',
      'Elastic Slider',
      'Counter',
      'Infinite Menu',
      'Stepper',
      'Bounce Cards'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Liquid Ether',
      'Prism',
      'Dark Veil',
      'Light Pillar',
      'Silk',
      'Floating Lines',
      'Light Rays',
      'Pixel Blast',
      'Color Bends',
      'Aurora',
      'Plasma',
      'Particles',
      'Gradient Blinds',
      'Grid Scan',
      'Beams',
      'Pixel Snow',
      'Lightning',
      'Prismatic Burst',
      'Galaxy',
      'Dither',
      'Faulty Terminal',
      'Ripple Grid',
      'Dot Grid',
      'Threads',
      'Hyperspeed',
      'Iridescence',
      'Waves',
      'Grid Distortion',
      'Ballpit',
      'Orb',
      'Letter Glitch',
      'Grid Motion',
      'Squares',
      'Liquid Chrome',
      'Balatro'
    ]
  }
];
