import { Blocks, Box, LayoutTemplate, Bot, Component } from 'lucide-react';

/**
 * Static presentation metadata for the on-domain Pro showcase (/pro, /pro/:section).
 *
 * The actual catalogue (items, counts, previews, deep links) is NOT stored here.
 * it comes from `public/pro-manifest.json`, which is generated by the Pro app.
 * Keep this file to copy, ordering and icons so the manifest stays the source of
 * truth and can refresh without a code change.
 *
 * `label`       short nav label (the sidebar already sits under a "Pro" heading).
 * `pageTitle`   heading used on /pro/:section, which can differ from the nav label.
 * `countKey`    manifest count for the real item total (variants, not cards).
 * `categoryCountKey` set when the page lists categories rather than items.
 * `manifestKey` maps a section to its array on the manifest.
 * `groupKey`    optional key on `manifest.groups` used to build filter chips.
 * `variantLevel` render one card per variant instead of one per category.
 * `previewDir`  asset folder under `assets.baseUrl` holding variant previews.
 */
/**
 * Headline totals for the static Pro copy: the docs sidebar card, the mobile
 * bar and the announcement message.
 *
 * The /pro pages read live counts straight from pro-manifest.json, but these
 * three surfaces render on every docs page, where fetching a 340KB manifest to
 * fill in one line of text is not worth it. Keep these in step with
 * `counts` in public/pro-manifest.json whenever the catalogue grows.
 */
export const PRO_COUNTS = {
  components: 150,
  blocks: 280,
  appUi: 300,
  templates: 15,
  agentKit: 20,
  total: 765
};

/** Full breakdown, used where there is room for the whole list. */
export const PRO_SUMMARY =
  `${PRO_COUNTS.components} components, ${PRO_COUNTS.blocks} blocks, ${PRO_COUNTS.appUi} app UI blocks, ` +
  `${PRO_COUNTS.templates} templates and ${PRO_COUNTS.agentKit} agent skills`;

export const PRO_SECTIONS = [
  {
    slug: 'components',
    label: 'Components',
    pageTitle: 'Pro Components',
    icon: Component,
    manifestKey: 'components',
    groupKey: 'components',
    countKey: 'components',
    countNoun: 'components',
    tagline: 'Animated React components, the full set',
    description:
      'Shaders, cursor effects, galleries and text animations, in Tailwind or vanilla CSS. One CLI command drops the real source into your project.',
    seoTitle: 'React Bits Pro - Animated React Components',
    seoDescription:
      'Browse every animated React component in React Bits Pro. Shader effects, custom cursors, galleries, 3D text and more, with Tailwind and CSS variants.',
    proPath: '/docs/components'
  },
  {
    slug: 'blocks',
    label: 'Blocks',
    pageTitle: 'Animated Blocks',
    icon: Blocks,
    manifestKey: 'blocks',
    variantLevel: true,
    previewDir: 'blocks',
    countKey: 'blocks',
    countNoun: 'blocks',
    categoryCountKey: 'blockCategories',
    categoryNoun: 'categories',
    tagline: 'Full page sections, ready to ship',
    description:
      'Heroes, pricing, FAQs, footers and every other section a landing page needs, each a single editable file. A full page is a few minutes of work.',
    seoTitle: 'React Bits Pro - React UI Blocks & Page Sections',
    seoDescription:
      'Browse React UI blocks from React Bits Pro: hero sections, pricing tables, FAQs, footers, auth screens and more, each in multiple ready-to-ship variants.',
    proPath: '/docs/blocks'
  },
  {
    slug: 'app-ui',
    label: 'App UI',
    countLabel: 'App UI Blocks',
    pageTitle: 'Application UI',
    icon: Box,
    manifestKey: 'appUi',
    variantLevel: true,
    previewDir: 'app-ui',
    countKey: 'appUi',
    countNoun: 'app UI blocks',
    categoryCountKey: 'appUiCategories',
    categoryNoun: 'categories',
    tagline: 'The interface layer for real products',
    description:
      'Dashboards, data tables, AI chat, forms, overlays and auth flows. Shared theme tokens restyle every screen at once, so they land looking like your product.',
    seoTitle: 'React Bits Pro - React App UI, Dashboards & AI Interfaces',
    seoDescription:
      'Dashboards, data tables, AI chat interfaces, forms, overlays and auth flows for React apps, from React Bits Pro.',
    proPath: '/docs/app-ui'
  },
  {
    slug: 'templates',
    label: 'Templates',
    pageTitle: 'Templates',
    icon: LayoutTemplate,
    manifestKey: 'templates',
    freeCount: 1,
    countKey: 'templates',
    countNoun: 'templates',
    tagline: 'Complete sites, ready to deploy',
    description:
      'Full multi-page Next.js templates, wired end to end. Download the project, swap the copy, deploy. The Portfolio template is free.',
    seoTitle: 'React Bits Pro - React & Next.js Website Templates',
    seoDescription:
      'Complete React and Next.js templates from React Bits Pro: SaaS, agency, portfolio, finance, AI and security sites, with live previews. One template is free.',
    proPath: '/docs/templates'
  },
  {
    slug: 'agent-kit',
    label: 'Agent Kit',
    sidebarLabel: 'Skills',
    /* "Agent Kit items" reads more naturally beside the numeric count. */
    countLabel: 'Agent Kit Items',
    pageTitle: 'Agent Kit',
    icon: Bot,
    manifestKey: 'agentKit',
    freeCount: 1,
    countKey: 'agentKit',
    countNoun: 'skills, prompts & recipes',
    tagline: 'Give your AI agent real design taste',
    description:
      'Skills that teach Claude Code, Cursor and Copilot to build pages that look designed. They autoload once installed, so asking for the style is enough.',
    seoTitle: 'React Bits Pro - Agent Kit for Claude Code, Cursor & Copilot',
    seoDescription:
      'Design skills, prompts and recipes that teach AI coding agents to build well-designed React pages. Works with Claude Code, Cursor and Copilot. Includes a free skill.',
    proPath: '/docs/agent-kit'
  }
];

export const PRO_SECTION_MAP = Object.fromEntries(PRO_SECTIONS.map(s => [s.slug, s]));

/** Objection-handling FAQ for the Pro hub. Ordered by how often each one blocks a purchase. */
export const PRO_FAQ = [
  {
    q: 'Is the free React Bits going away?',
    a: 'No. Every component on this site stays free, open source and maintained. Pro is a separate library that sits on top of it, and it is what funds the free one.'
  },
  {
    q: 'Do I need to install a package?',
    a: 'No. The shadcn CLI copies real source files into your project, or you can paste them in by hand. There is no react-bits dependency to add or upgrade, and nothing to rip out later.'
  },
  {
    q: 'Can I use it on client work and SaaS?',
    a: 'Yes. One license covers one developer for unlimited commercial projects, including client work and your own products. The only thing you cannot do is repackage the code as a competing library or template.'
  },
  {
    q: 'Is it a subscription?',
    a: 'Your choice. Lifetime is a one-time payment that includes every future update. Annual is a yearly subscription you can cancel any time. Either way, code already in your project stays there permanently.'
  },
  {
    q: 'Can I match it to my brand?',
    a: 'Yes, and you restyle every app UI block at once. They share CSS custom properties for accent, base grey, font and radius, so a live theme panel with six presets changes all of them without editing a single file.'
  },
  {
    q: 'How does this work with AI?',
    a: 'Agents wire up logic well and invent visuals badly, so you hand them ours. Every file is readable, idiomatic source, and a SKILL.md teaches your agent the whole library so it installs the right piece instead of guessing.'
  },
  {
    q: 'What stack does it use?',
    a: 'Next.js 16, React 19, TypeScript and Tailwind CSS 4, with motion, GSAP or Three.js where an effect needs it. It is React-specific, so it will not drop into Vue or Svelte as-is.'
  },
  {
    q: 'How often does it get updates?',
    a: 'Every month, across the whole library: components, blocks, app UI, templates and agent skills. Lifetime buyers get all of it at no extra cost, so your library keeps growing without you doing anything.'
  },
  {
    q: 'Can I judge the quality before paying?',
    a: 'Yes, and you should. The full catalogue is previewable here, the Pro docs are open to browse, and a complete template plus an agent skill are free. All sales are final, so please look first.'
  }
];

/**
 * Testimonials for the Pro hub, sourced from pro.reactbits.dev.
 *
 * Ordered so the strongest purchase proof (paid and would buy again, real
 * workflow with templates plus the agent skill) is dealt to the top of the
 * three columns rather than buried mid-scroll.
 */
/** Short blurbs for the two free items; manifest descriptions run too long for a card. */
export const PRO_FREE_COPY = {
  'portfolio-template': 'A complete personal portfolio, animated and ready to deploy.',
  'terminal-dark': 'Teaches your agent to build dev-tool pages that look like real software.'
};

export const PRO_TESTIMONIALS = [
  {
    handle: '@shadcn',
    avatar: 'https://pbs.twimg.com/profile_images/1593304942210478080/TUYae5z7_400x400.jpg',
    text: 'Everything about this is next level.',
    url: 'https://x.com/shadcn/status/1962854085587275932'
  },
  {
    handle: '@JuzzBk',
    avatar: 'https://pbs.twimg.com/profile_images/2067474986286424064/hOqiQRjz_400x400.jpg',
    text: "I don't really invest in so many digital products but this is one of those I won't ever regret.",
    url: 'https://x.com/JuzzBk/status/2076791586374181298'
  },
  {
    handle: '@MajorBaguette',
    avatar: 'https://pbs.twimg.com/profile_images/1671069355872796677/l5NFDO8o_400x400.png',
    text: 'A product so well crafted that it becomes an instant classic in your stack? My last one is React Bits.',
    url: 'https://x.com/MajorBaguette/status/1968616151421776293'
  },
  {
    handle: '@juandadotdev',
    avatar: 'https://pbs.twimg.com/profile_images/1953194119045545984/HIxpl7MK_400x400.jpg',
    text: "Paid once, and he keeps shipping updates. Easiest value I've gotten from any tool.",
    url: 'https://x.com/juandadotdev/status/2082117331103162412'
  },
  {
    handle: '@MaartenSlebos',
    avatar: 'https://pbs.twimg.com/profile_images/2082020722793197568/_n43BeHN_400x400.jpg',
    text: 'I start from a template and customize it with my agents using the React Bits skill. Makes my life so much easier.',
    url: 'https://x.com/MaartenSlebos'
  },
  {
    handle: '@NeuralAA',
    avatar: 'https://pbs.twimg.com/profile_images/1907255350740369408/hs1GAAg2_400x400.jpg',
    text: 'Incredibly creative components, with the hard things made fluid and performant.',
    url: 'https://x.com/NeuralAA/status/2083487874196890071'
  },
  {
    handle: '@gregberge_',
    avatar: 'https://pbs.twimg.com/profile_images/1722358890807861248/75S7CB3G_400x400.jpg',
    text: 'React Bits: A stellar collection of React components to make your landing pages shine ✨',
    url: 'https://x.com/gregberge_/status/1896425347866059041'
  },
  {
    handle: '@justine_chang39',
    avatar: 'https://pbs.twimg.com/profile_images/2038292993556533248/p5lPVFXv_400x400.jpg',
    text: '@davidhdev is cooking some of the most beautiful components I have ever seen with React Bits.',
    url: 'https://x.com/justine_chang39/status/1968195651457724550'
  },
  {
    handle: '@theorcdev',
    avatar: 'https://pbs.twimg.com/profile_images/1756766826736893952/6Gvg6jha_400x400.jpg',
    text: "If you haven't seen React Bits yet, you need to. David is grinding harder than any warrior you've seen before.",
    url: 'https://x.com/theorcdev/status/1963881697205715128'
  },
  {
    handle: '@adeelibr',
    avatar: 'https://pbs.twimg.com/profile_images/1859351824576245760/k0aPYRHF_400x400.jpg',
    text: 'An amazing list of curated react components - from text animation, hover effects, to really cool backgrounds.',
    url: 'https://x.com/adeelibr/status/1969517849065422974'
  },
  {
    handle: '@nolansym',
    avatar: 'https://pbs.twimg.com/profile_images/1882700369060642816/CU7TLjtQ_400x400.jpg',
    text: 'Genuinely blown away by the animation quality.',
    url: 'https://x.com/nolansym'
  },
  {
    handle: '@GibsonSMurray',
    avatar: 'https://pbs.twimg.com/profile_images/2072160805710143488/J0uL0tQ1_400x400.jpg',
    text: 'React Bits has got to be the most artistic component lib I have seen in a while 🤌',
    url: 'https://x.com/GibsonSMurray/status/1889909058838339626'
  },
  {
    handle: '@Logreg_n_coffee',
    avatar: 'https://pbs.twimg.com/profile_images/1554006663853592576/Gxtolzbo_400x400.jpg',
    text: 'Literally the coolest library for React.',
    url: 'https://x.com/Logreg_n_coffee/status/1889573533425991992'
  },
  {
    handle: '@syskey_dmg',
    avatar: 'https://pbs.twimg.com/profile_images/1918646280223608832/nqBF4zh__400x400.jpg',
    text: 'A sleek, minimal, and super dev-friendly React component library. Clean UI, easy to use, and perfect for modern projects.',
    url: 'https://x.com/syskey_dmg/status/1929762648922398754'
  },
  {
    handle: '@mrterrycarson',
    avatar: 'https://pbs.twimg.com/profile_images/833004663142117377/SjMv4aVQ_400x400.jpg',
    text: 'Great one to have for sure.',
    url: 'https://x.com/mrterrycarson/status/2077031484712493338'
  }
];

/**
 * Templates withheld from the on-domain showcase. The manifest is generated by
 * the Pro app, so curation lives here rather than being edited into the data.
 */
export const HIDDEN_TEMPLATE_SLUGS = ['ai-app-template', 'minimal-landing'];

/**
 * Hand-picked reel line-up.
 *
 * The hub reel is the first thing a visitor sees, so it is curated rather than
 * sampled: these are the entries that read best as a small, moving 16:9 tile,
 * favouring colour, depth and obvious motion over dense grey screenshots.
 * Order is the display order. Anything missing from the manifest is skipped,
 * and an empty list falls back to an even sample of the section.
 *
 * Keys are slugs, except Agent Kit which is `<kind>-<slug>` because slugs
 * repeat across skills, prompts and recipes.
 */
export const PRO_REEL_FEATURED = {
  components: [
    'particle-morph',
    'aurora-beam',
    'eclipse',
    'chroma-blinds',
    'inverted-dome',
    'reel-gallery',
    'long-exposure',
    'silk-waves',
    'glowing-ridges',
    'liquid-bars',
    'glass-reveal',
    'glass-tiles',
    'tile-reveal',
    'neon-reveal',
    'ascii-ripple',
    'neural-tunnel'
  ],
  blocks: [
    'bento-31',
    'hero-23',
    'bento-2',
    'pricing-6',
    'bento-37',
    'hero-24',
    'bento-1',
    'social-proof-3',
    'bento-20',
    'cta-5',
    'bento-34',
    'ecommerce-6',
    'bento-12',
    'stats-5',
    'bento-5',
    'showcase-2'
  ],
  'app-ui': [
    'filtering-1',
    'monitoring-6',
    'analytics-14',
    'analytics-5',
    'dashboard-1',
    'dashboard-3',
    'kanban-1',
    'monitoring-10',
    'tool-calls-3',
    'scheduling-6',
    'file-manager-2',
    'analytics-13',
    'data-table-2',
    'chat-2',
    'editor-4',
    'command-menu-3'
  ],
  'agent-kit': [
    'skill-neobrutalism',
    'skill-playful-motion',
    'skill-swiss-grid',
    'skill-terminal-dark',
    'skill-editorial',
    'skill-luxury-serif',
    'skill-apple-minimal',
    'skill-corporate-trust',
    'prompt-fintech',
    'prompt-consumer-hardware',
    'prompt-ecommerce-brand',
    'recipe-saas-homepage'
  ],
  templates: []
};

/**
 * Maps a free docs category to its counterpart in the Pro Components catalogue,
 * used by the footer at the bottom of every component page.
 *
 * `group` is a value from `manifest.groups.components`; `groups` combines
 * closely related groups for a broader category story. Omitting both counts
 * the complete Pro component catalogue.
 */
export const CATEGORY_PRO_GROUPS = {
  backgrounds: { group: 'Backgrounds', noun: 'backgrounds' },
  'text-animations': { group: 'Text', noun: 'text animations' },
  animations: {
    groups: ['3D & Shaders', 'Cursor Effects'],
    filter: 'Animations',
    noun: 'animation components'
  },
  components: { noun: 'components' }
};

/**
 * Contextual upgrade stories for the free docs. The previews are deliberately
 * hand-picked: a small, relevant set converts better than repeating a generic
 * inventory total on every page.
 */
export const PRO_UPSELLS = {
  backgrounds: {
    eyebrow: 'More backgrounds in Pro',
    title: 'Build the atmosphere, not just the backdrop.',
    description: 'Editable shader scenes with responsive defaults and one-command installs.',
    path: '/docs/components?category=Backgrounds',
    noun: 'backgrounds',
    featured: [
      { slug: 'glass-tiles', name: 'Glass Tiles' },
      { slug: 'radial-liquid', name: 'Radial Liquid' },
      { slug: 'vortex', name: 'Vortex' }
    ]
  },
  'text-animations': {
    eyebrow: 'More text effects in Pro',
    title: 'Give every headline a point of view.',
    description: 'Expressive headline effects for reveals, scroll moments and hero typography.',
    path: '/docs/components?category=Text',
    noun: 'text animations',
    featured: [
      { slug: 'glitch-text', name: 'Glitch Text' },
      { slug: '3d-text-reveal', name: '3D Text Reveal' },
      { slug: 'speeding-text', name: 'Speeding Text' }
    ]
  },
  animations: {
    eyebrow: 'More interactions in Pro',
    title: 'Turn movement into a signature.',
    description: 'Smooth cursor effects and responsive interactions, ready for real projects.',
    path: '/docs/components?category=Cursor%20Effects',
    noun: 'cursor effects',
    featured: [
      { slug: 'circles', name: 'Circles' },
      { slug: 'dither-cursor', name: 'Dither Cursor' },
      { slug: 'chroma-blinds', name: 'Chroma Blinds' }
    ]
  },
  components: {
    eyebrow: 'More UI in Pro',
    title: 'Go from a component to a complete product.',
    description: 'Polished UI components, page blocks and app screens built to work together.',
    path: '/docs/components',
    noun: 'components',
    featured: [
      { slug: 'reel-gallery', name: 'Reel Gallery' },
      { slug: 'shader-card', name: 'Shader Card' },
      { slug: 'comparison-slider', name: 'Comparison Slider' }
    ]
  },
  default: {
    eyebrow: 'React Bits Pro',
    title: 'Build the whole product with one library.',
    description: 'Components, page blocks, application UI, templates and AI skills, ready to launch.',
    path: '/',
    noun: 'components',
    featured: [
      { slug: 'aurora-beam', name: 'Aurora Beam' },
      { slug: 'smooth-cursor', name: 'Smooth Cursor' },
      { slug: 'circle-gallery', name: 'Circle Gallery' }
    ]
  }
};
